export const SET_RANDOM_JOKE = 'SET_RANDOM_JOKE'
export const SET_RANDOM_JOKE_STATUS = 'FETCHING_RANDOM_JOKE'

export const SAVE_JOKE = 'SAVE_JOKE'
export const DELETE_JOKE = 'DELETE_JOKE'
export const SET_SAVED_JOKES = 'SET_SAVED_JOKES'
export const SET_SAVED_JOKES_STATUS = 'SET_SAVED_JOKES_STATE'
